---

# +-------------------------------------------------+
# |             MCPEToDiscord - VER 1.3             |
# |-------------------------------------------------|
# |                                                 |
# | Made by : Jackthehack21 (gangnam253@gmail.com)  |
# |                                                 |
# | Build   : 055#A                                 |
# |                                                 |
# | Details : This plugin is aimed to give players  |
# |           A simple but fun view of what plugins |
# |           Can do to modify your MCPE experience.|
# |                                                 |
# +-------------------------------------------------+


language: 'english' # english, spanish, german, chinese

debug: false

discord: "true"

webhook_url: ""
webhook_name: "MCPE Webhook"
webhook_playerChat?: true
webhook_playerJoin?: true
webhook_playerLeave?: true
webhook_playerDeath?: true

webhook_playerChatFormat: "[ {player} | {time} ] : {msg}"
webhook_playerJoinFormat: "{player} Joined the server !"
webhook_playerLeaveFormat: "{player} Left the server !"
webhook_playerDeathFormat: "{player} Died !"

other_pluginEnabled?: true
other_pluginDisabled?: true
other_pluginEnabledFormat: "Plugin Enabled !"
other_pluginDisabledFormat: "Plugin Disabled !"
...
